name: Deploy to prod

on:
  push:
    branches: [main]

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
      - name: 'Display package.json'
        run: cat ./package.json
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Display updated package.json'
        run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: [bump-version]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Sync Code to Deployment Directory
        run: |
          rsync -avz --delete \
          /home/github/actions-runner/_work/blindtus-web/blindtus-web/ \
          /home/website/www/blindtus-apps/web

      - name: Install, Build, and Restart App
        working-directory: /home/website/www/blindtus-apps/web
        run: |
          npm ci
          npm run lint
          npm run build
          pm2 startOrRestart ./scripts/pm2.config.js

  notification:
    name: Notif
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [bump-version, deploy]

    steps:
      - name: Notify Discord on Failure
        uses: sarisia/actions-status-discord@v1
        if: ${{ needs.deploy.result == 'failure' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          noprefix: true
          title: 'Failed: Deploy to Prod'
          description: |
            Build and deploy to blindtus.com failed.
          color: 0xC14F4F
          username: GitHub Notif

      - name: Notify Discord on Success
        uses: sarisia/actions-status-discord@v1
        if: ${{ needs.deploy.result == 'success' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          noprefix: true
          title: 'Success: Deploy to Prod'
          description: 'Build and deploy to blindtus.com - ${{ needs.bump-version.outputs.newTag }}'
          color: 0x03bafc
          username: GitHub Notif
