name: Deploy to prod

on:
  push:
    branches: [main]

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    outputs:
      newTag: ${{ steps.version-bump.outputs.newTag }}

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: 'Display package.json'
        run: cat ./package.json

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Output New Tag'
        run: |
          echo "New tag: ${{ steps.version-bump.outputs.newTag }}"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [bump-version]

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd /home/website/www/blindtus-apps/web

            # Reset any local changes and pull the latest code
            git reset --hard
            git pull origin main

            # Ensure correct ownership and permissions
            sudo chown -R github:developer .
            sudo chmod -R g+rw .
            sudo chmod g+s .

            # Install dependencies and build the project
            npm ci
            npm run lint
            npm run build

            # Restart the application
            pm2 startOrRestart ./scripts/pm2.config.js

  notification:
    name: Notif
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [bump-version, deploy]

    steps:
      - name: Notify Discord on Failure
        uses: sarisia/actions-status-discord@v1
        if: ${{ needs.deploy.result == 'failure' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          noprefix: true
          title: 'Failed: Deploy to Prod'
          description: |
            Build and deploy to blindtus.com failed.
            **Error Message:** Deployment failed during execution.
          color: 0xC14F4F
          username: GitHub Notif

      - name: Notify Discord on Success
        uses: sarisia/actions-status-discord@v1
        if: ${{ needs.deploy.result == 'success' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          noprefix: true
          title: 'Success: Deploy to Prod'
          description: |
            Build and deploy to blindtus.com - ${{ needs.bump-version.outputs.newTag }}
          color: 0x03bafc
          username: GitHub Notif
